### ISSUE TITLE
In places where we have a use-value restart for abiguous method matches, also have a delete-function restart

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/cepl#100]
Will speed up development when you can just delete the old version.

**Comment by stacksmith** [comment]
Yes.  I will make an argument that use-value is a bad solution.

In practice, you will often interactively modify a shader's signature and update the pipeline feed.  At this point, you get an error, unless the pipeline definition was explicit (for no great reason).  

Consider the current use-value situation.  You select the right shader, but it fixes nothing in the long run - next time you recompile the shader or the pipeline - without even changing anything - you will get the restart again.  A clean reload 'magically' fixes it.  The user is confused and thinks the system is buggy.

The right thing to do have a delete-function restart, and nuke the old one.  Now the image (Lisp image) state matches what will happen at a clean reload. 

----------
# HOWEVER

When will you ever delete the new shader you just compiled?  This has a bad smell.

I still think that silently selecting the newest shader in ambiguous cases may actually be the right solution, oddly enough.  By creating a new shader, you indicate the intent to use it when called by name and no type in the pipeline.  This is what will be used on a clean reload if you deleted it.

@cbaggers, I understand that you feel it is not a rational choice that may be inconsistent with the rest of the system.  Is it possible there are two distinct cases here?

- compiling an ambiguous `def-g->` into a system with multiple shaders;
- modifying a shader to a different signature with an existing `def-g->`.

In the first case, you can signal an error, as there is an ambiguity in the source.  
In the second case, the user is making interactive changes to an existing system and indicates intent to use the latest-compiled shader.  If def->g comes before the shader in source, the latest shader is selected and a warning issued.  Semantically this makes sense.

This _may_ appear weird, as the sequence dictates the outcome.  However, in Lisp, the sequence does dictate the outcome, and you can get into all kinds of crap by creating a symbol in the wrong package.  Or redefine a function with different parameters, which _will_ be called, by the way (unless it is a generic function).

**Comment by stacksmith** [comment]
I will make an argument that both use-value and delete-function restarts are bad solutions.

The problem is that there two distinct use cases:
* Interactive: the user modifies and recompiles an existing shader, creating a pipeline ambiguity.
* Batch: the user loads a file consisting of multiple shaders and an ambiguous def-g->.

# use-value is bad for both.

In the interactive case, the source for the old shader is deleted/changed.  You should nuke it, not select something you no longer have the source for, right?

In batch case, you should not have a choice.  This is clearly an error condition: you should disambiguate the def-g->, or delete one of the shaders from source.  

# delete-function is bad for both

In the interactive case, it does the job. **BUT WHY WOULD YOU EVER DELETE A SHADER YOU JUST WROTE?**

In batch case, you should not be allowed to delete anything from the GPU - you have an error that needs fixing in the source.

# PROPOSED SOLUTION
Whether interactive or in source, the problem has to do with the sequence of events.  There are two distinct cases:
- compiling an ambiguous `def-g->` into a system with multiple shaders.  **ERROR!**
- modifying a shader to a different signature with an existing `def-g->`. **WARN AND SELECT NEWEST**.

@cbaggers, I understand that you feel it is not a rational choice that may be inconsistent with the rest of the system.  But I think the system is more consistent than with the other two solutions.  Consider:

* Interactive - it just does the right thing. You obviously meant to use the just-compiled shader.
* batch - it just does the right thing.  You have an error in your source.

There is a weird case, where in source, you def-g-> first, and then define multiple shaders, and the latest one is used (in interactive use, that is exactly what you want).  This is just like a funcall to a yet-undefined function, followed by multiple definitions.  Although there is a possible overload, the def-g-> without a type indicates that the programmer is not thinking of it as a generic function!

**Please reconsider this issue.**  Having banged my head against it as a 'user', I feel pretty confident that both use-value and delete-function restart solutions are wrong.  It is your system, of course, and you are free to do as you wish, but I think you are making a mistake.

Can you think of a situation where my proposal would be more inconsistent then the other solutions on the table?

**Comment by cbaggers** [comment]
Thanks for the very thorough writeup. It certainly make sense on paper so I'll trying getting it into code and taking it for a spin.

To speak to a few of your questions:

> BUT WHY WOULD YOU EVER DELETE A SHADER YOU JUST WROTE?

BECAU.. *cough* because `delete-function` was intended to let you choose which function to undefine. It still may be wrong but I have done the following before.

**Comment by cbaggers** [comment]
Thanks for the very thorough writeup. It certainly make sense on paper so I'll trying getting it into code and taking it for a spin.

To speak to a few of your questions:

> BUT WHY WOULD YOU EVER DELETE A SHADER YOU JUST WROTE?

BECAU.. *cough* because `delete-function` was intended to let you choose which function to undefine. It still has the problems from before, but wont always be the oldest definition that needs to be deleted, just an older one.

**Comment by stacksmith** [comment]
I thought you'd say that, but didn't want to make my plea longer than it was.

I think this is a separate issue from what to do while compiling.

Yes, there are situations when you need to delete some of the functions.  In my scenario, you can delete the old function to avoid warnings, or after compiling an errored file as described above

You can explicitly invoke function management routines to fix a bad situation.

**Comment by cbaggers** [comment]
Agreed. I will get rid of `use-value` and not add `remove-function` restarts.

I think the ability to choose the conflict-policy is nice though, that was we get your solution (and it's benefits) and a more cautious mode for when people need it. 

Thoughts?

**Comment by stacksmith** [comment]
Sorry about incessant editing... I've been up since crack of ass and have trouble verbalizing.
So you agree... Great.  I suppose you can have a strict mode which errors, but perhaps a smarter solution is to have a strict def-g-> mode that requires types?  
Let me take a step back... Changing the signature of a shader requires feeding it different types, so why not just insist that def-g-> requires types always?  It's just one more place to fix when making changes; I don't think you can change types and feed it different data interactively without breaking the pipeline anyway...

**Comment by cbaggers** [comment]
Sure, that's even easier and no ambiguity. I prefer this over even over the other options

**Comment by stacksmith** [comment]
Honestly, recompiling shaders with the same signature while CEPL is running is really cool.  Changing the shaders and pipeline feeders is a big job, so it makes sense to note in the pipeline creation which shader you are using - it's built-in documentation that matches reality.

**Comment by cbaggers** [comment]
ah fair point, I'm typing before thinking I guess. Right I'll take your branch, add my twist and then we can play with it :)

Further changes can come after play.

**Comment by cbaggers** [comment]
btw thanks for taking the time to hammer this out with me. I love being able to bounce the ideas regardless of which way it goes. Also the above log will be super useful when I next forget my reasoning behind things :)

**Comment by stacksmith** [comment]
Hang on, we are out of sync...  I am thinking fuck both our fixes - just require type information for def-g-> and we never get the ambiguity. No?

**Comment by cbaggers** [comment]
haha ok, man I got lost there. I'm going to do both on different branches as they are simple changes and we can pick the one that feels good

**Comment by stacksmith** [comment]
Sure.  To summarize, the fix I proposed earlier, select latest shader and warn + error on def-g-> recompile, will do the right thing, but is pretty hard to describe, as you've seen.  My latest proposal requires type on def-g->, so a tiny bit more typing, but it is obvious at a glance what shaders are being used.

**Comment by stacksmith** [comment]
Note that my fix just prints the warning as I was having trouble with (warn ...) taking control away, possibly due to the fact that we are inside a macro expansion...

**Comment by cbaggers** [comment]
So here is a the strict version. https://github.com/cbaggers/cepl/commit/6a5279f87de12854993056c96d1d1a685ba95ee5

I have tried to make the errors as helpful as possible.

**Comment by stacksmith** [comment]
Sorry, I am a bit stupid with github.  What's a good way for me to get at it, with git command-line...  Thanks

**Comment by cbaggers** [comment]
I always use `magit` for emacs but it should be `git fetch`, `git checkout feature-strict-defpipe` or something similar

**Comment by cbaggers** [comment]
Ugh implementing the other version isn't simple after all. Without going too deep, it would require all def-g-> listening to changes to gpu-functions that it doesnt use just in case they become a match for the unqualfied stage name.

I'd like to swing the dictator hammer at this point and just say users must fully qualify the stage types.
It's simpler to explain, simpler to implement and the behaviour is totally predictable.

**Comment by cbaggers** [comment]
hehe. given that there were two options (auto & static) and I've just said I'm not implementing the first one. I guess I have swung the dictator hammer already. I'll get that branch ready to merge and do it.

**Comment by stacksmith** [comment]
Agreed.

I started thinking again, but stopped myself.  Hammer blows echo through the room.

Oh, I have a fix for some issues with your branch in a pull request...

**Comment by cbaggers** [comment]
thanks

**Comment by cbaggers** [comment]
Blam. Changes made.
