### ISSUE TITLE
Add more implicit uniforms to CEPL shaders

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/cepl#123]
They will be stripped automatically if not used.

What things would be good candidates?

**Comment by cbaggers** [comment]
viewport size

**Comment by stacksmith** [comment]
Is there any reason to do that?  The library user can add whatever they need, no?  Otherwise we are stepping into host territory.  I suppose if we define the host interface, host data reported (mouse, keyboard, windowing info, etc) is up for grabs.  Although I still think the user should do that (unless special support is required to accomplish that, which I don't think is the case).

I am also still ambivalent about the earmuff requirement.  In Lisp, all specials are bound and visible from any function, so why can't we pretend to just see them from varjo code?

**Comment by cbaggers** [comment]
> Does varjo allow free variable capture for lexical variables
sadly no. CEPL uses `#'symbol-value` when trying to work out the type and that has this note in the CLHS
> symbol-value can be used to get the value of a constant variable. symbol-value cannot access the value of a lexical variable.

> I am also still ambivalent about the earmuff requirement. 
I'm pretty sure the requirement should be removed. I just need to do it. I'll file a ticket

> Is there any reason to do that?
The user can add whatever they want. There are just a few thing that feel like they should always have been there and viewport-dimensions is probably the biggest one for me. We have `gl_FragCoord` & `gl_FragDepth` which both are transformed based of the viewport-dimesions and depth-range but no way to unnormalize them without passing in uniforms explicitly.

Your probably right and I'm just annoyed that I had to type a bunch of things :p

**Comment by cbaggers** [comment]
@stacksmith I have let this sit in my a while and I agree with you. I'm also changing the logic of the earmuff requirement. I now only check that the symbol is `boundp` (which means it's a has to be a special variable) 

Thanks for sticking with this issue, It's taken me a while to chew over.

Fixed on varjo master
