### ISSUE TITLE
CEPL should request OpenGL 3.1 (or higher) by default

### ISSUE THREAD

**Issue by podiki** [cbaggers/cepl#144]
As per Issue #66, as CEPL requires version 3.1 at least, so use a default value for `requested-gl-version` in `cepl:repl`. This way calling `(cepl:repl)` without arguments works in more cases.

At least for me on 2 different machines (both Linux) with Intel graphics the default OpenGL context is for 3.0. Running with an Nvidia card the default is 4.5, so `(cepl:repl)` works without specifying a version. This has something to do with the graphics driver, but the Intel graphics supports up to version 4.5, it just has to be explicitly requested.

Anyway, minor enhancement to make the default requested version match the minimum CEPL requires would be good.

**Comment by cbaggers** [comment]
Good call. I'm reworking the API for CEPl's hosts at the moment so I'll make sure this gets in there.
Thanks!

**Comment by podiki** [comment]
Sounds good. Just starting to play with CEPL, but very excited to get away from just writing plain OpenGL in lisp. Thanks!

**Comment by cbaggers** [comment]
I think what I'm going to do is say that repl always requires a core context. We don't use the legacy stuff anyway so this will probably help us.

I guess I need to do the thing where we create a context just to check the available versions. The reason is that if we request a 3.1 context we will get it, even if the platform supports higher (macOS is like this)

Bah this stuff is the least fun and always a pita :D

**Comment by podiki** [comment]
Yeah, I think sticking to core context is a good idea (might as well try to drop legacy stuff, anyone who really wants it can go down to the opengl level directly). It does seem like there is a lot of variation between GPUs and drivers for what context version they will give you. On an integrated Intel GPU, requesting any version seemed to just give the highest it could go, and while by default it would only be 3.0. Meanwhile on Nvidia it'll default to 4.5. So yeah...a messy affair.

**Comment by Arseniusz** [comment]
I also can't run cepl on both my Linux machines because of OpenGL version.
Here is  glxinfo | grep OpenGL

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 12.0.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 12.0.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 12.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by podiki** [comment]
@Arseniusz yes, that's exactly the problem, that the "default" profile for some cards is something lower than the full capabilities of the GPU (3.0 instead of 3.3, here). For now you can request a specific version, i.e. `(cepl:repl width height gl-version)` where `gl-version` is `3.3`. That should work, unless things have changed recently in the API.

**Comment by Arseniusz** [comment]
@podiki Thanks a lot! (cepl:repl 300 300 3.1) works fine, but (cepl:repl 300 300 3.0) don't. Does it mean that "real" OpenGL version on my machine is 3.3?

**Comment by cbaggers** [comment]
3 doesnt work as the minimum version CEPL allows is 3.1. This doesnt tell you what version your machine supports sadly. Try `glxinfo | grep "OpenGL version"` instead

**Comment by cbaggers** [comment]
Next release of CEPL's hosts (CEPL.SDL2 & CEPL.GLOP) will require core contexts. If you don't specify a version it will search for the best version you machine supports (from 4.5 -> 3.3)

Hopefully this will make things a bit simpler & more stable

Thanks for your patience with this one

**Comment by podiki** [comment]
Great, sounds good! Strange how much variation there can be between hardware/drivers/OSes, quite annoying. Glad you got it done!
