### ISSUE TITLE
Unable to create buffer texture with initial contents

### ISSUE THREAD

**Issue by podiki** [cbaggers/cepl#147]
Linux (Arch) x86_64, v4.5 OpenGL context. While doing `(make-texture (loop repeat 1 collect (v! 1.0 1.0 1.0)) :dimensions 1 :element-type :vec3)` works just fine, adding in `:buffer-storage t` it fails with the following error and (partial) backtrace below. Seems like the `:element-type` is being discarded at some point, and if you try without `:element-type :vec3` CEPL cannot guess the correct type.

```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CEPL.TYPES:ELEMENT-TYPE (4)>
when called with arguments
  ((#(1.0 1.0 1.0))).
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY] Retry calling the generic function.
 1: [RETRY] Retry SLIME REPL evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT] abort thread (#<THREAD "new-repl-thread" RUNNING {1002053093}>)

Backtrace:
  0: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION CEPL.TYPES:ELEMENT-TYPE (4)> (#(1.0 1.0 1.0))) [fast-method]
      Locals:
        SB-PCL::ARGS = ((#(1.0 1.0 1.0)))
        GENERIC-FUNCTION = #<STANDARD-GENERIC-FUNCTION CEPL.TYPES:ELEMENT-TYPE (4)>
  1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION CEPL.TYPES:ELEMENT-TYPE (4)> ((#(1.0 1.0 1.0))))
      Locals:
        SB-PCL::ARGS = ((#(1.0 1.0 1.0)))
        SB-PCL::GF = #<STANDARD-GENERIC-FUNCTION CEPL.TYPES:ELEMENT-TYPE (4)>
  2: (CEPL.TEXTURES::GEN-BUFFER-TEX-INITIAL-CONTENTS (#(1.0 1.0 1.0)) (1) :RGB32F NIL NIL NIL NIL 1 NIL)
      Locals:
        CEPL.TEXTURES::CUBES = NIL
        DIMENSIONS = (1)
        DIMENSIONS#1 = (1)
        CEPL.TEXTURES::IMAGE-FORMAT = :RGB32F
        CEPL.TEXTURES::INITIAL-CONTENTS = (#(1.0 1.0 1.0))
        CEPL.TEXTURES::LAYER-COUNT = 1
        CEPL.TEXTURES::MIPMAP = NIL
        CEPL.TEXTURES::MULTISAMPLE = NIL
        PIXEL-FORMAT = NIL
        CEPL.TEXTURES::RECTANGLE = NIL
  3: (MAKE-TEXTURE (#(1.0 1.0 1.0)) :DIMENSIONS 1 :ELEMENT-TYPE :VEC3 :MIPMAP NIL :LAYER-COUNT 1 :CUBES NIL :RECTANGLE NIL :MULTISAMPLE NIL :IMMUTABLE T :BUFFER-STORAGE T :GENERATE-MIPMAPS T :PIXEL-FORMAT ..
      Locals:
        #:.DEFAULTING-TEMP. = 1
        #:.DEFAULTING-TEMP.#1 = :VEC3
        #:.DEFAULTING-TEMP.#2 = NIL
        #:.DEFAULTING-TEMP.#3 = 1
        #:.DEFAULTING-TEMP.#4 = NIL
        #:.DEFAULTING-TEMP.#5 = NIL
        #:.DEFAULTING-TEMP.#6 = NIL
        #:.DEFAULTING-TEMP.#7 = T
        #:.DEFAULTING-TEMP.#8 = T
        #:.DEFAULTING-TEMP.#9 = T
        #:.DEFAULTING-TEMP.#10 = NIL
        DIMENSIONS = (1)
        INITIAL-CONTENTS = (#(1.0 1.0 1.0))
```

**Comment by cbaggers** [comment]
Another good catch. Thankyou.

The problem here is in `#'gen-buffer-tex-initial-contents` (`textures.lisp` line 538). I am assuming a certain type for the initial-contents. I need to rewrite it so that:
- if the initial-contents are a c-array and no element-type/image-format provided we assert the args are valid and then just make a gpu-array from the c-array 
- if the initial-context are a c-array and an element-type/image-format is provided then check that it matches the c-array, assert the args are valid and make the gpu-array.
- if the initial-context are a buffer backed gpu-array and no element-type/image-format are provided then just assert the args are valid and use that gpu-array, .
- if the initial-context are a buffer backed gpu-array and an element-type/image-format is provided then check that it matches the c-array, assert the args are valid and make the gpu-array.
- if the initial-contents are lisp data call make-c-array (passing in the element-type, or if it's an image format convert it to an element-type first) then extract the final element-type, assert the args are valid and make the gpu-array

This will be easy to fix. I'll post back here when I've done it. It's possible that it will be a few days from now as I'm busy tonight and then away for the weekend (I may be able to sneak some lisping in during that time)

**Comment by podiki** [comment]
Great, thanks. I did look through the code and ended up at `gen-buffer-tex-initial-contents` as well at some point, and seemed like something was incomplete. Sounds like you got it figured out and is pretty straightforward. Let me know if you need any testing or anything else. In the meantime I just `push-g` the contents after creating the texture, works great.

**Comment by cbaggers** [comment]
Cool, this actually helped be find another related bug in the buffer-texture initialization. I'll push some fixes tonight

**Comment by podiki** [comment]
Sounds good, thanks!

**Comment by cbaggers** [comment]
Should have been fixed by https://github.com/cbaggers/cepl/commit/56f5bb7ec9b6d041f42cfe6c4e8f79eed74b2c50

**Comment by podiki** [comment]
I believe you, but will be unable to test until #148 is resolved, sorry!

**Comment by podiki** [comment]
Works for me, thanks!

**Comment by cbaggers** [comment]
Yay, thanks again for the help
