### ISSUE TITLE
How does one compile CEPL?

### ISSUE THREAD

**Issue by pipsqueaker** [cbaggers/cepl#241]
I'm new to lisp, but this project has me excited. I'd like to be able to compile it myself so that I'll be able to play around with it, but I'm run into some issues.

What I've done so far 

- Clone this repo
- Switch to the release-quicklisp branch
- Add this project to my `quicklisp/local-projects` directory (via symlink)

When I try to do `(ql:quickload :cepl)` however, I get errors. The ones I run into off the bat look like that 

```
; in: DEFUN CALC-VECTOR-BASE-ALIGNMENT
;     (2 (* 2 (%CEPL.TYPES::MACHINE-UNIT-SIZE %CEPL.TYPES::ELEM-TYPE)))
; 
; caught ERROR:
;   illegal function call
```

and originate from the `ecase=` statement at the bottom of `core/types/layouts.lisp`. I couldn't find any references to `ecase=` online, so I replaced it with the (standard?) `ecase` and that seemed to fix those errors.

The next error I ran into looked like this

```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "WITH-UNKNOWN-FIRST-CLASS-FUNCTIONS-ALLOWED" not found in the VARJO package.
;   
;       Line: 133, Column: -1, File-Position: 6016
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM
;                 for "file /home/myname/Code/glisp/cepl/core/pipelines/gpu-functions.lisp"
;                 {10084DA333}>
```

Seeing this, I went over and checked [the symbols](https://github.com/cbaggers/varjo/blob/master/package.lisp) (? unsure what to call them) that varjo provides.

`with-unknown-first-class-functions-allowed` appears on the master branch there, but if I check out the `release-quicklisp` branch I see that it doesn't appear there.

At this point I'm kind of confused and feel like there must be something I'm missing, since installing `cepl` from quicklisp remotely worked just fine. If possible, could you go over how exactly I can compile this project?

Sorry, I know this must seem mundane- hopefully it's not too much work to explain

**Comment by cbaggers** [comment]
If you want to use the latest release, please simply run `(ql:quickload :cepl)` from your repl. This will pull all the dependencies and put them in the right places. CEPL (like GL) doesnt know how to make a window or context on its own so you have to use a 'host'. The most common one used is sdl2. To use it, `(ql:quickload :cepl.sdl2)`. <- this will also pull cepl so you can use `(ql:quickload :cepl.sdl2)` instead of `(ql:quickload :cepl)`. 

Usually people just put it in the `:depends-on` section of their `.asd` file.

I set up a project using CEPL in [this video](https://youtu.be/PXR4t8BuUwY?t=1m13s) so hopefully that helps a bit. I also go through `quick-project` in this [very old video](https://youtu.be/SPgjgybGb5o)

Hmm I just noticed that at the end of your question you mention it works from Quicklisp. Quicklisp only pulls down code so even when using quicklisp you are compiling the code on your own system.

The dependencies for CEPL are as follows so you will need all of these on your system in order for CEPL to build:

- cffi
- cl-fad
- cl-opengl
- cl-ppcre
- documentation-utils
- fn
- ieee-floats
- named-readtables
- varjo
- rtg-math
- closer-mop
- bordeaux-threads

however all of these are in quicklisp so it should be fine. I wouldnt recommend cloning them all locally as it just makes keeping them up to date harder (I dont clone any of the ones im not working on)

To speak to your specific errors `ecase=` is in `rtg-math` project (in the `%rtg-math` package IIRC). `Symbol "WITH-UNKNOWN-FIRST-CLASS-FUNCTIONS-ALLOWED" not found in the VARJO package` means that you have an out of date version of varjo around somewhere.

I'd recommend you run: 
- `(ql:update-client)`
- `(ql:update-all-dists)`
- `(ql:register-local-projects)`

and then `(asdf:system-relative-pathname :varjo "./")` will tell you where your varjo is. 

Once again, unless you are planning on hacking on CEPL (which would be awesome!) I would stick to quicklisp as the versions of the various libs are tested together before each month's release and dependencies are handled for you.

I hope this helps, sorry for the first half being a bit off track :)

**Comment by pipsqueaker** [comment]
I'd hoped to play around with CEPL's source yeah (don't get too excited, for now at least I have no idea what's going on :)

Anyways, it looks like the quicklisp update commands fixed whatever was wrong- I can now load the packages with `ql:quickload`, and the `asdf:system-relative-pathname` command points me to my local sources. Thanks a ton!

**Comment by cbaggers** [comment]
No probs
