### ISSUE TITLE
question about my glsl version

### ISSUE THREAD

**Issue by stereosphere** [cbaggers/cepl#54]
I am pretty sure this is a problem on my side, but maybe you can help. I've put the error message and the results of glxinfo below. glxinfo shows some results for 3.3. Any ideas how I can resolve this?

Thanks,

Michael

Here is the error I get when I try to compile the basic-3d-objects example:
Error compiling vertex-shader: 
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

#version 330

struct G_PC {
    vec3 POS;
    vec4 COL;
};
My computer is running Ubuntu 14.04 with an NVidia graphics card:
mfleming@poincare:~$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.0.4
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 11.0.4
OpenGL shading language version string: 1.30

**Comment by stereosphere** [comment]
Never mind about this. I'm using a newer graphics card and it's working well. This is a fantastic project, thanks.

**Comment by cbaggers** [comment]
Hey there @stereosphere, so sorry I didnt reply. I know this is closed now (and I'm stoked it is working for you) but I wanted to get back to you anyway.

So yeah the stuff around versions is a bit crappy right now. Technically CEPL needs GL v3.3 or up as I make heavy use of sampler objects (especially in the branch I'm working on), however when cepl compiles the gpu functions it tells the compiler (Varjo) to use version `330` by default.

This can be customized with `&context :310` in the pipeline signature but I haven't really tested it. Even if you do that the next issue is with Varjo. When I made varjo there was no machine readable version of the spec. I spent days dumping data from the glsl spec pdf and then fixing it so it could be used. As you can imagine I was so sick of it that I cut corners, and the easiest place to cut corners was the version info. If you look in the `varjo/language/functions.lisp` file you will see `&context (:330 :440)` on most of the functions, this means the function is valid for those versions. I need to go fix this information.

Luckily a while back some awesome folks made this site http://docs.gl/ which was WAY easier to scrape than the official spec, so I made this https://github.com/cbaggers/gl-to-sexp/blob/master/spec/glsl.sexp so we now have the full spec, with version data, in a decent format. Now I just need to take the time to regenerate all the Varjo function definitions from this data. My `glsl.sexp` still needs a little massaging to get the version info in a good format for this next step but that should be an afternoons work.

After that is done though, Varjo will be able to generate valid GLSL for any version (including webgl :) ) which will be ace.

Thanks again for looking at CEPL, and thanks for asking this as it's motivated me to look at the spec files again. Drop me a line if you need anything.

Have fun!

**Comment by stereosphere** [comment]
> Have fun!
>
I definitely am having fun. I have a very simple project that I'm 
working on. I'm drawing 3d spheres with normals (based on the 
basic-3d-shapes demo). It's really great to be able to change the 
shaders on the fly. Can any other system do that?

It's late here in California, so I'm turning in.

Thanks for all your effort!

Michael

**Comment by cbaggers** [comment]
Great to hear! Yeah other systems can do shader reload, but there are various ways of doing it so comparing is tricky. 

You could just file watch and reupload the shader when saving, but if you change the inputs/outputs then you have to rewrite all the gl pumbing code to use them so that would ruin the experimenting experience there are also game engines that do the code and plumbing, but then I feel it's a bit too abstracted from just writing functions.

I still haven't seen many general purpose projects that make GL feel native whilst also not adding magic (like abstracting away the pipeline). I guess in some languages feeling native would necessitate such abstraction, for example in haskell you would want a monadic pipeline handling the context etc. Common Lisp is nice in the way that it expects you to be imperative and stateful in some places.

I am looking forward to when CEPL stabilizes a bit so we can play with these abstractions over pipelines in projects that are separate from CEPL but just generate code that CEPL then compiles for you.

Ahhh it's gonna be cool!
