### ISSUE TITLE
The variable PROG-1 is unbound.

### ISSUE THREAD

**Issue by ebrasca** [cbaggers/cepl#59]
`(def-g-> prog-1 ()
  #'vert #'frag)`

> The variable PROG-1 is unbound.
   [Condition of type UNBOUND-VARIABLE]

**Comment by smithzvk** [comment]
Apologies if you already know this and are just reporting the bug, but I figured out the current syntax for this and thought I would share.  I believe this is because the way you define a pipeline has changed, probably long ago, but the examples haven't.  This is written as so, at least in what's in my version of the Quicklisp dist:

    (defpipeline prog-1 () (g-> #'vert #'frag))

Hopefully this will help others that are trying to use Cepl before it completely settles down.

**Comment by cbaggers** [comment]
Ah! this looks like quicklisp hasnt got the new stuff yet:

`(defpipeline prog-1 () (g-> #'vert #'frag))` is the old syntax

`(def-g-> prog-1 () #'vert #'frag)` is the new one. Hmm I wonder when the next quicklisp release is

**Comment by ebrasca** [comment]
Thank you.
