### ISSUE TITLE
New backend: cepl.drm-gbm

### ISSUE THREAD

**Issue by malcolmstill** [cbaggers/cepl#81]
I've been working on [EGL](https://github.com/malcolmstill/cl-egl), [DRM](https://github.com/malcolmstill/cl-drm) and [GBM](https://github.com/malcolmstill/cl-gbm) bindings for Common Lisp and have started work on [a backend](https://github.com/malcolmstill/cepl.drm-gbm) that uses these so that cepl can draw directly to the Linux framebuffer.

One issue is that this should (probably) always have width and height of the screen. I wonder whether [`make-context`](https://github.com/cbaggers/cepl/blob/master/core/context/make.lisp) should set its width and height not based on the requested width and height but on values returned by `request-context`?

**Comment by cbaggers** [comment]
Hi Malcolm, first off this looks very cool! What are your plans for this?

Regarding screen sizes, I recently added window-size to the host api, as it's not something CEPL is in control of. On the CEPL side users would call `window-dimensions` which calls `cepl.host:window-size`. That function is expected to have been populated by the host and to return the width and height of the window as a list. Here is the implementation for the [SDL2 host](https://github.com/cbaggers/cepl.sdl2/commit/bdf7818d16312bf6958c640ea8396a3e9d43f57d). I hope this doesn’t cause you any issues.

Is the window size something you can query for the host end? I remember than Shinmera has some code that was aiming to abstract over [querying monitor sizes](https://github.com/Shirakumo/libmonitors/tree/master/src) but it looks like the linux part is X11 specific.

I should definitely add some info to the docs to tell people to check the size of the window they got as there is no guarantee that the host would have been able to give them what they asked for.

Also my apologies that the code around the GL context in CEPL is so bad. It was a part I knew so little about and so I did the absolute minimum to get it working and have avoided in since. If you need something though please let me know as it would be a great motivation to get some work done there.

**Comment by malcolmstill** [comment]
I put this backend together because I'm working on a Common Lisp Wayland compositor and I want to use CEPL for the rendering. I have the compositor working using SDL (via cepl.sdl2) so that it runs on top of X. The DRM/GBM backend will allow running the compositor without X (as is intended); I'm still working on wrapping libinput which is the final piece to make that backend usable.

I saw the `cepl.host:window-size` but couldn't get it working...I think it's probably because I don't have cepl up to date.

I could have some could that queries the dimensions of the screen and then calls `cepl:repl` with those dimensions I just wondered whether it made sense that `make-context` creates a framebuffer dependent on dimensions returned from `cepl.host:request-context`, say

```
  (setf *gl-context* context
            *gl-window* (window context)
            (slot-value context 'fbo) (cepl.fbos::%make-default-framebuffer
                                       (cepl.host:window-size) t t))
```

**Comment by cbaggers** [comment]
Sounds useful. I'm going to dump some thoughts below to see if they make sense:
- CEPL is about GL only, like GL it only knows about contexts & buffers. It doesn't know about windows or displays so it has a host.
- Hosts know about windows and how to make a context. Some seem to have ways of getting the display mode info too https://wiki.libsdl.org/SDL_GetCurrentDisplayMode so maybe this should live here.

The alternative of having the host handle it is having another layer that the host can use. But this feels like things are getting a bit too complicated and I think that layer would not end up tidier than having the host be responsible for it.

One thing I would like to maintain is that CEPL doesn't have platform/host specific info, only stuff that pertains to GL as this matches GL more closely and makes it much easier to port across platforms/lisp-implementations.

What are your thoughts on this? 

p.s. This is my first time looking at Wayland's api but could `wl_output` be helpful here?

**Comment by cbaggers** [comment]
The new host api has added more feature & functions that can be queried from CEPL. Ping me for details. The host api is versioned so using CEPL with your host should still work fine.

I'm closing this issue for now
